name: xAI-FL-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - torchvision=0.19.0
  - tensorboard>=2.4.1
  - numpy=2.1.0
  - scipy=1.14.1
  - scikit-learn=1.5.1
  - tqdm=4.66.5
